# Generated by Django 5.2.6 on 2025-11-11 12:22

import django.db.models.deletion
import phonenumber_field.modelfields
import shared.models.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Первый номер телефона')),
                ('secondary_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Второй номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Эл. почта')),
                ('addres', models.CharField(blank=True, max_length=128, verbose_name='Адрес')),
                ('work_time_text', models.CharField(blank=True, max_length=32, verbose_name='Время работы')),
                ('map_coordinates', models.CharField(blank=True, help_text='Формат: <code>53.556350, 49.216210</code>', max_length=32, validators=[shared.models.validators.map_coordinates_format], verbose_name='Координаты на карте')),
            ],
            options={
                'verbose_name': '📠 | Контакты компании',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Указывайте человеко-читаемый текст. По умолчанию также используется для HTML Title и H1.', max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('h1', models.CharField(blank=True, help_text='По умолчанию для H1 используется Name.', max_length=127, verbose_name='H1 Заголовок')),
                ('html_title', models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title')),
                ('add_sitename_to_html_title', models.BooleanField(default=True, verbose_name='Добавить название сайта к HTML Title?')),
                ('html_description', models.TextField(blank=True, verbose_name='HTML Description')),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='Поддерживается django template рендеринг!<details style="width: 70%; padding-left: 1rem;"><summary style="margin-left: -1rem;">Подробнее</summary>\n\t\tЕсли активирован рендеринг, текст из этого поля будет обработан через django template рендеринг.<br>\n\t\tЭто означает, что вы можете использовать здесь темплейт инструменты, такие как:\n\t\t<li>Теги <code>{% if %}</code>, <code>{% for %}</code> и другие.</li>\n\t\t<li>\n\t\t\tПеременные, например: <code>{{ page.extra_context }},\n\t\t\t{{ global.pages.index }}, {{ global.extra_context }}</code> и т.д.\n\t\t</li>\n\t\t<li>\n\t\t\tА также теги обработки, например: <code>...|default:"..."</code>,\n\t\t\t <code>...|truncatechars:40</code> и многие другие.\n\t\t</li>\n\t\tКонтекст будет такой же, как и на странице, на которой будет выводится этот текст.<br>\n\n\t\tВажно: функционал рендеринга реализуется в каждом темплейте отдельно, через специальный template-тег.\n\t\tЭто означает, что <b>нет гарантии</b>, что фронтендер добавил эту обработу <i>там</i>.\n\t\tСогласуйте это вместе с фронтендером.<br>Если же вы используете стандартный темплейт <code>core/generic/page.html</code>, то рендеринг гарантирован.</details>', verbose_name='Контент')),
                ('is_generic_page', models.BooleanField(default=False, help_text='✅: Будет автоматически доступно по url <code>"/<slug>/"</code>, требует заданного <code>Template name</code>. Используйте для простых страниц, которым не нужен свой View.<br>❌: Выбирайте, когда для обработки страницы нужно использовать кастомный View.<br><br>Влияет на логику работы полей <code>URL Pathname</code> и <code>Template name</code>.', verbose_name='Это динамически-добавляемая страница?')),
                ('url_name', models.CharField(blank=True, help_text='<code>is_generic_page:</code>✅ - Игнорируется, потому <b>должно быть</b> пустым.<br><code>is_generic_page:</code>❌ - <code>name</code> того url, который обрабатывает эту страницу.<details style="padding-left: 1rem;">Например, в ваших <code>urlpatterns</code> есть <code>path("fun-path/", some_view, name="your-name")</code>, тут указываете <code>"your-name"</code>.<br>Вы всё корретно указали, метод <code>get_absolute_url()</code> вернёт ссылку на этот path, т.е <code>"/fun-path/"</code>.<br><br>Для index страницы по полному пути "/", а также для generic страниц с кастомным URL в принципе, увы, но вы вынуждены создавать свои собственные url и view, даже если вам не нужна дополнительная логика.</details>', max_length=64, verbose_name='URL Name')),
                ('template_name', models.CharField(blank=True, help_text='<code>is_generic_page:</code>✅ - Путь к файлу, включая расширение. По умолчанию используется <code>core/generic/page.html</code><br><code>is_generic_page:</code>❌ - Игнорируется, потому <b>должно быть</b> пустым.', validators=[shared.models.validators.template_exists_in_root_directory], verbose_name='Название django-темплейта')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'страницы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='JBrony Site', help_text='В основном используется в base.html', max_length=128, verbose_name='Название сайта')),
                ('favicon', models.ImageField(blank=True, upload_to='favicon')),
                ('robots_txt_content', models.TextField(blank=True, verbose_name='Содержимое Robots.txt')),
                ('head_script', models.TextField(blank=True, help_text='Этот текст будет вставлен в блок &ltscript&gt в &lthead&gt каждой html-страницы сайта', verbose_name='Скрипт')),
            ],
            options={
                'verbose_name': '⚙ | Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='TelegramSendingChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_env_name', models.CharField(help_text='Название ENV переменной с токеном этого бота. Также проверяется существование токена в телеграм системе.', validators=[shared.models.validators.env_variable_name], verbose_name='ENV-переменная с токеном')),
                ('chat_id', models.CharField(help_text='Если был передан некорректный ID чата - ошибка возникнет только при первой попытке отправить сообщение, будте внимательны!', max_length=32, verbose_name='ID чата')),
                ('specialization', models.CharField(choices=[('new_request_notifications', 'Уведомления о новых заявках'), ('logs', 'Логи')], help_text='Может быть только один канал для конкретной специализации', unique=True, verbose_name='Специализация канала')),
            ],
            options={
                'verbose_name': 'Канал отправки сообщений в Telegram',
                'verbose_name_plural': '📡 | Каналы отправки сообщений в Telegram',
            },
        ),
        migrations.CreateModel(
            name='ExtraContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='Ключ')),
                ('value', models.CharField(verbose_name='Значение')),
                ('page', models.ForeignKey(blank=True, help_text='Если указать здесь страницу - ключ будет доступен через объект страницы и будет исключён из глобального контекста (<code>global.extra_context</code>).<br>Тем не менее, он всё также будет доступен глобально, но уже через <code>global.pages</code>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_context_manager', to='core.page', verbose_name='Привязать к странице')),
            ],
            options={
                'verbose_name': 'Дополнительный контекст',
                'verbose_name_plural': 'Дополнительный контекст',
            },
        ),
    ]
