# Generated by Django 5.2.6 on 2025-11-13 09:42

import shared.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_generic_page',
            field=models.BooleanField(default=False, help_text='✅: Будет автоматически доступно по url <code>"/&ltslug&gt/"</code>, требует заданного <code>Template name</code>. Используйте для простых страниц, которым не нужен свой View.<br>❌: Выбирайте, когда для обработки страницы нужно использовать кастомный View.<br><br>Влияет на логику работы полей <code>URL Pathname</code> и <code>Template name</code>.', verbose_name='Это динамически-добавляемая страница?'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='robots_txt_content',
            field=models.TextField(blank=True, default='User-Agent: *\nDisallow: /admin/\n', verbose_name='Содержимое Robots.txt'),
        ),
        migrations.AlterField(
            model_name='telegramsendingchannel',
            name='token_env_name',
            field=models.CharField(help_text='Название ENV переменной с токеном этого бота.', validators=[shared.models.validators.env_variable_name], verbose_name='ENV-переменная с токеном'),
        ),
    ]
