# Generated by Django 5.2.6 on 2025-11-12 16:48

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False, help_text='Если уведомление о создании новой заявки успешно ушло в телеграм — автоматически считается "Увиденным". Иначе, считается что заявку не увидели и нужно вручную поставить эту галочку админке, когда её увидят.', verbose_name='Увидено персоналом')),
                ('requestener_name', models.CharField(max_length=24, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('comment', models.TextField(blank=True, max_length=512, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения заявки')),
            ],
            options={
                'verbose_name': 'Заявка на обратную связь',
                'verbose_name_plural': 'Заявки на обратную связь',
            },
        ),
    ]
