# Generated by Django 5.2.6 on 2025-11-12 16:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Указывайте человеко-читаемый текст. По умолчанию также используется для HTML Title и H1.', max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('_h1', models.CharField(blank=True, help_text='По умолчанию для H1 используется Name.', max_length=127, verbose_name='H1 Заголовок')),
                ('_html_title', models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title')),
                ('add_sitename_to_html_title', models.BooleanField(default=True, verbose_name='Добавить название сайта к HTML Title?')),
                ('html_description', models.TextField(blank=True, verbose_name='HTML Description')),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='articles')),
                ('content', tinymce.models.HTMLField(verbose_name='Содержимое')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Статьи, чья дата публикации ещё не наступила, не будут отображаться на сайте', verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='BusinessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saplings_in_hectare', models.PositiveSmallIntegerField(default=1000, help_text='Используется в калькуляторе стоимости')),
            ],
            options={
                'verbose_name': '🛠 | Конфиг бизнес параметров',
            },
        ),
        migrations.CreateModel(
            name='HectarePatronage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('hectares', models.PositiveSmallIntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество гектар')),
                ('price_in_thousands', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена в тысячах')),
                ('summary', models.TextField(max_length=256, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'варианты шефства гектаров',
                'verbose_name_plural': 'шефство гектара',
            },
        ),
        migrations.CreateModel(
            name='HowItsWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('text', models.CharField(max_length=128, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'элемент "Как это работает"',
                'verbose_name_plural': 'элементы "Как это работает"',
            },
        ),
        migrations.CreateModel(
            name='Parthners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('svg_code', models.TextField(verbose_name='SVG Код')),
            ],
            options={
                'verbose_name': 'партнёр',
                'verbose_name_plural': 'партнёры',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('summary', models.TextField(max_length=256, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'услуги',
                'verbose_name_plural': 'услуга',
            },
        ),
        migrations.CreateModel(
            name='HectarePatronageBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='business.hectarepatronage')),
            ],
            options={
                'verbose_name': 'бонус',
                'verbose_name_plural': 'бонусы',
            },
        ),
    ]
