# Generated by Django 5.2.6 on 2025-11-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hectarepatronage',
            options={'ordering': ['order'], 'verbose_name': 'шефство гектара', 'verbose_name_plural': 'варианты шефства гектаров'},
        ),
        migrations.AlterModelOptions(
            name='hectarepatronagebonus',
            options={'ordering': ['order'], 'verbose_name': 'бонус', 'verbose_name_plural': 'бонусы'},
        ),
        migrations.AlterModelOptions(
            name='howitsworkitem',
            options={'ordering': ['order'], 'verbose_name': 'элемент "Как это работает"', 'verbose_name_plural': 'элементы "Как это работает"'},
        ),
        migrations.AlterModelOptions(
            name='parthners',
            options={'ordering': ['order'], 'verbose_name': 'партнёр', 'verbose_name_plural': 'партнёры'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'услуги', 'verbose_name_plural': 'услуга'},
        ),
    ]
